[package]
name = "RVM"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
libc = "0.2"